table inet isas {
  set management_v4 { type ipv4_addr; flags interval; elements = { replace-management-cidr } }
  chain input {
    type filter hook input priority -10; policy drop;
    iifname "lo" accept
    ct state established,related accept
    ip protocol icmp accept
    ip6 nexthdr ipv6-icmp accept
    tcp dport 22 ip saddr @management_v4 accept
    ct original proto-dst 443 tcp dport 8444 accept
    tcp dport { 3000, 4222, 4317, 4318, 5432, 6432, 8443, 8444, 9000 } drop
  }
  chain prerouting {
    type nat hook prerouting priority dstnat; policy accept;
    tcp dport 443 redirect to :8444
  }
}
