set skip on lo0
ext_if = "replace-at-deploy"
block in log quick on $ext_if proto tcp from any to any port { 3000, 4222, 4317, 4318, 5432, 6432, 8443, 8444, 9000 }
rdr pass on $ext_if proto tcp from any to ($ext_if) port 443 -> 127.0.0.1 port 8444
