FROM postgres:16.4-bookworm@sha256:e62fbf9d3e2b49816a32c400ed2dba83e3b361e6833e624024309c35d334b412
COPY apps/bff/migrations /isas/migrations
COPY --chmod=0555 apps/bff/bin/run-migrations.sh /isas/run-migrations.sh
USER postgres
ENTRYPOINT ["/isas/run-migrations.sh"]
