#!/bin/sh
set -eu

: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}"
: "${KEYCLOAK_DB_PASSWORD:?KEYCLOAK_DB_PASSWORD is required}"
for name in ISAS_DB_P0_PASSWORD ISAS_DB_AUTH_P1_PASSWORD ISAS_DB_P1_PASSWORD ISAS_DB_P2_PASSWORD ISAS_DB_OPS_PASSWORD; do
  eval "value=\${$name:-}"
  [ -n "$value" ] || { echo "$name is required" >&2; exit 78; }
done

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  -v keycloak_password="$KEYCLOAK_DB_PASSWORD" \
  -v p0_password="$ISAS_DB_P0_PASSWORD" \
  -v auth_password="$ISAS_DB_AUTH_P1_PASSWORD" \
  -v p1_password="$ISAS_DB_P1_PASSWORD" \
  -v p2_password="$ISAS_DB_P2_PASSWORD" \
  -v ops_password="$ISAS_DB_OPS_PASSWORD" <<'SQL'
CREATE ROLE auth_context_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE app_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE local_support_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE app_user LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOBYPASSRLS PASSWORD :'p1_password';
CREATE ROLE auth_role LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOBYPASSRLS PASSWORD :'auth_password';
CREATE ROLE p0_user LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOBYPASSRLS PASSWORD :'p0_password';
CREATE ROLE p2_user LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOBYPASSRLS PASSWORD :'p2_password';
CREATE ROLE ops_user LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOBYPASSRLS PASSWORD :'ops_password';
CREATE ROLE keycloak_user LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOBYPASSRLS PASSWORD :'keycloak_password';
GRANT app_user TO p0_user, p2_user;
GRANT auth_context_owner, app_owner, local_support_owner TO postgres;
CREATE DATABASE keycloak OWNER keycloak_user;
REVOKE CONNECT ON DATABASE isas FROM PUBLIC;
GRANT CONNECT ON DATABASE isas TO app_user, auth_role, p0_user, p2_user, ops_user;
SQL
