host.hostname = "$name.isas.internal";
persist;
mount.devfs;
devfs_ruleset = 4;
vnet;
exec.clean;
exec.start = "/bin/sh /etc/rc";
exec.stop = "/bin/sh /etc/rc.shutdown jail";
exec.timeout = 120;
stop.timeout = 120;
enforce_statfs = 2;
allow.raw_sockets = 0;
allow.mount = 0;
allow.mount.devfs = 0;
allow.mount.zfs = 0;
allow.sysvipc = 0;
children.max = 0;

isas_db { path = "/jails/isas/database/root"; vnet.interface = "e_db_b"; exec.prestart = "/usr/local/libexec/isas-jail-net prepare db"; exec.poststart = "/usr/local/libexec/isas-jail-net address db isas_db 10.77.0.13"; exec.poststop = "/usr/local/libexec/isas-jail-net destroy db"; }
isas_idp { path = "/jails/isas/identity/root"; vnet.interface = "e_idp_b"; exec.prestart = "/usr/local/libexec/isas-jail-net prepare idp"; exec.poststart = "/usr/local/libexec/isas-jail-net address idp isas_idp 10.77.0.14"; exec.poststop = "/usr/local/libexec/isas-jail-net destroy idp"; }
isas_objq { path = "/jails/isas/object-queue/root"; vnet.interface = "e_objq_b"; exec.prestart = "/usr/local/libexec/isas-jail-net prepare objq"; exec.poststart = "/usr/local/libexec/isas-jail-net address objq isas_objq 10.77.0.15"; exec.poststop = "/usr/local/libexec/isas-jail-net destroy objq"; }
isas_app { path = "/jails/isas/app/root"; vnet.interface = "e_app_b"; exec.prestart = "/usr/local/libexec/isas-jail-net prepare app"; exec.poststart = "/usr/local/libexec/isas-jail-net address app isas_app 10.77.0.12"; exec.poststop = "/usr/local/libexec/isas-jail-net destroy app"; }
isas_edge { path = "/jails/isas/edge/root"; vnet.interface = "e_edge_b"; exec.prestart = "/usr/local/libexec/isas-jail-net prepare edge"; exec.poststart = "/usr/local/libexec/isas-jail-net address edge isas_edge 10.77.0.11"; exec.poststop = "/usr/local/libexec/isas-jail-net destroy edge"; }
isas_otel { path = "/jails/isas/telemetry/root"; vnet.interface = "e_otel_b"; exec.prestart = "/usr/local/libexec/isas-jail-net prepare otel"; exec.poststart = "/usr/local/libexec/isas-jail-net address otel isas_otel 10.77.0.16"; exec.poststop = "/usr/local/libexec/isas-jail-net destroy otel"; }
