isas_net = "10.77.0.0/24"
ext_if = "replace-at-deploy"
table <isas_edge> const { 10.77.0.11 }
table <isas_app> const { 10.77.0.12 }
table <isas_database> const { 10.77.0.13 }
table <isas_identity> const { 10.77.0.14 }
table <isas_object_queue> const { 10.77.0.15 }
table <isas_telemetry> const { 10.77.0.16 }

block in log quick on bridge_isas all
rdr pass on $ext_if proto tcp from any to ($ext_if) port 443 -> 10.77.0.11 port 443
pass in quick on bridge_isas proto tcp from <isas_edge> to <isas_app> port 3000
pass in quick on bridge_isas proto tcp from <isas_app> to <isas_database> port { 5432, 6432 }
pass in quick on bridge_isas proto tcp from <isas_app> to <isas_identity> port 8443
pass in quick on bridge_isas proto tcp from <isas_app> to <isas_object_queue> port { 4222, 9000 }
pass in quick on bridge_isas proto tcp from $isas_net to <isas_telemetry> port { 4317, 4318 }
block in log quick on bridge_isas from $isas_net to $isas_net
