jail:isas_db:memoryuse:deny=8G
jail:isas_idp:memoryuse:deny=2G
jail:isas_objq:memoryuse:deny=4G
jail:isas_app:memoryuse:deny=4G
jail:isas_edge:memoryuse:deny=1G
jail:isas_otel:memoryuse:deny=4G
jail:isas_db:maxproc:deny=2048
jail:isas_app:maxproc:deny=1024
jail:isas_idp:maxproc:deny=512
jail:isas_objq:maxproc:deny=512
jail:isas_edge:maxproc:deny=256
jail:isas_otel:maxproc:deny=512
